name: Analisar dados

on:
  schedule:
    - cron: "15 */6 * * *"
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Baixar dados
        run: |
          curl -s -o repos.json https://raw.githubusercontent.com/hvmpro-core/perfil-dados/main/repos.json

      - name: Ver conteúdo
        run: cat repos.json

      - name: Instalar jq (garantia)
        run: sudo apt-get install -y jq

      - name: Processar dados
        run: |
          TOTAL_REPOS=$(jq length repos.json)
          TOTAL_STARS=$(jq '[.[].stargazers_count] | add' repos.json)

          echo "{" > resumo.json
          echo "\"total_repos\": $TOTAL_REPOS," >> resumo.json
          echo "\"total_stars\": $TOTAL_STARS" >> resumo.json
          echo "}" >> resumo.json

      - name: Ver resultado
        run: cat resumo.json

      - name: Commit e push
        run: |
          git config user.name "bot"
          git config user.email "bot@github.com"
          git add .
          git commit -m "update analise" || echo "sem mudanças"
          git push
